// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/holla-world/typing-golib/xzero/xcmd"
	"github.com/holla-world/typing-golib/xzero/xcmd/engine"

	{{.importPackages}}
)

func RegisterHandlers(svr *xcmd.Server, svc *svc.ServiceContext) {
	{{.routesAdditions}}
}
