// Code generated by goctl. DO NOT EDIT.
// Code generated by goctl. DO NOT EDIT.
// Code generated by goctl. DO NOT EDIT.
package {{.PkgName}}

import (
	"github.com/holla-world/typing-golib/xzero/cmd"
	"github.com/spf13/cobra"
	"github.com/zeromicro/go-zero/core/service"

    {{.ImportPackages}}
)

{{range .Groups}}
func {{.GroupName}}(initializer func(cmd *cobra.Command) error) cmd.DeamonExec {
	return func(cmd *cobra.Command, args []string) error {
		err := initializer(cmd)
		if err != nil {
			return err
		}

		svc.NewServiceContext(xsvc.GetServiceContext())
		cfg := svc.GetConfig()
		svcCtx := svc.GetServiceContext()

		group := service.NewServiceGroup()
		defer group.Stop()
		{{range .Handlers}}group.Add(handler.New{{.}}ConsumerHandler(cfg.Consumers["{{.}}"],svcCtx))
		{{end}}

		group.Start()
		return nil
	}
}
{{end}}